config: conf/train.yaml
print_config: false
log_level: INFO
dry_run: false
iterator_type: sequence
output_dir: exp/tts_train_raw_phn_pypinyin_g2p_phone
ngpu: 1
seed: 0
num_workers: 1
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: null
dist_rank: null
local_rank: 0
dist_master_addr: null
dist_master_port: null
dist_launcher: null
multiprocessing_distributed: false
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
collect_stats: false
write_collected_feats: false
max_epoch: 200
patience: null
val_scheduler_criterion:
- valid
- loss
early_stopping_criterion:
- valid
- loss
- min
best_model_criterion:
-   - valid
    - loss
    - min
-   - train
    - loss
    - min
keep_nbest_models: 5
grad_clip: 1.0
grad_noise: false
accum_grad: 1
no_forward_run: false
resume: true
train_dtype: float32
log_interval: null
pretrain_path: []
pretrain_key: []
num_iters_per_epoch: null
batch_size: 20
valid_batch_size: null
batch_bins: 3750000
valid_batch_bins: null
train_shape_file:
- exp/tts_stats_raw_phn_pypinyin_g2p_phone/train/text_shape.phn
- exp/tts_stats_raw_phn_pypinyin_g2p_phone/train/speech_shape
valid_shape_file:
- exp/tts_stats_raw_phn_pypinyin_g2p_phone/valid/text_shape.phn
- exp/tts_stats_raw_phn_pypinyin_g2p_phone/valid/speech_shape
batch_type: numel
valid_batch_type: null
fold_length:
- 150
- 240000
sort_in_batch: descending
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
train_data_path_and_name_and_type:
-   - dump/raw/tr_no_dev/text
    - text
    - text
-   - dump/raw/tr_no_dev/wav.scp
    - speech
    - sound
valid_data_path_and_name_and_type:
-   - dump/raw/dev/text
    - text
    - text
-   - dump/raw/dev/wav.scp
    - speech
    - sound
allow_variable_data_keys: false
max_cache_size: 0.0
valid_max_cache_size: null
optim: adam
optim_conf:
    lr: 0.001
    eps: 1.0e-06
    weight_decay: 0.0
scheduler: null
scheduler_conf: {}
token_list:
- <blank>
- <unk>
- "\uFF30"
- "\uFF22"
- "\xFC"
- an
- ueng3
- '2'
- uen
- ei
- ua
- ao
- u
- ueng4
- uo
- ang
- ou
- v2
- ueng1
- o
- io1
- "\xFCn3"
- er
- ve4
- o3
- uai2
- uen3
- uen1
- uai3
- "\xFCe3"
- iou1
- iong2
- ia2
- uai1
- iong1
- "\xFCan1"
- "\xFCe1"
- v4
- ua3
- ia
- iong3
- uei3
- ua2
- ia3
- uei1
- o1
- o4
- "\xFCn2"
- un2
- er3
- "\xFCn1"
- uen4
- un3
- iu1
- "\xFCn4"
- uen2
- "\xFCan3"
- un4
- "\xFCan4"
- iu3
- ua1
- uei2
- "\uFF01"
- iou4
- iou2
- er4
- o2
- ei1
- iao2
- uang4
- "\xFC1"
- ui2
- v3
- uang2
- iong4
- un1
- ui1
- ua4
- ao2
- en
- a
- iu2
- uang1
- uang3
- "\xFCe2"
- in3
- "\uFF1F"
- uai4
- "\xFCe4"
- uan2
- ou2
- eng3
- ui3
- uan4
- a2
- ie2
- ong3
- iang2
- ie1
- in4
- iao1
- e1
- in2
- en4
- uan3
- "\xFC2"
- ing3
- i
- ei2
- ei3
- iang1
- er2
- ia4
- uo2
- "\xFC3"
- uan1
- ia1
- e3
- ong4
- ie4
- ai1
- en3
- iang3
- eng4
- iang4
- ao1
- ou1
- ang2
- ai3
- iu4
- "\xFCan2"
- ang3
- en1
- ong2
- uei4
- ei4
- iao3
- "\xFC4"
- an2
- ing4
- an3
- a3
- ie3
- an1
- ian3
- uo1
- ing1
- ou4
- ian1
- ou3
- eng1
- ang1
- in1
- a4
- eng2
- uo4
- u1
- ang4
- iou3
- iao4
- ian2
- u2
- ui4
- e2
- en2
- u3
- ing2
- ao4
- ong1
- an4
- ai2
- ao3
- uo3
- ian4
- p
- c
- a1
- ai4
- e4
- s
- k
- r
- i2
- f
- n
- u4
- ch
- i3
- i1
- q
- z
- m
- t
- g
- b
- e
- h
- i4
- x
- "\uFF0C"
- zh
- "\u3002"
- l
- j
- sh
- d
- <sos/eos>
odim: null
model_conf: {}
use_preprocessor: true
token_type: phn
bpemodel: null
non_linguistic_symbols: null
cleaner: null
g2p: pypinyin_g2p_phone
feats_extract: fbank
feats_extract_conf:
    fs: 24000
    fmin: 80
    fmax: 7600
    n_mels: 80
    hop_length: 300
    n_fft: 2048
    win_length: 1200
normalize: global_mvn
normalize_conf:
    stats_file: exp/tts_stats_raw_phn_pypinyin_g2p_phone/train/feats_stats.npz
tts: tacotron2
tts_conf:
    embed_dim: 512
    elayers: 1
    eunits: 512
    econv_layers: 3
    econv_chans: 512
    econv_filts: 5
    atype: location
    adim: 512
    aconv_chans: 32
    aconv_filts: 15
    cumulate_att_w: true
    dlayers: 2
    dunits: 1024
    prenet_layers: 2
    prenet_units: 256
    postnet_layers: 5
    postnet_chans: 512
    postnet_filts: 5
    output_activation: null
    use_batch_norm: true
    use_concate: true
    use_residual: false
    dropout_rate: 0.5
    zoneout_rate: 0.1
    reduction_factor: 1
    spk_embed_dim: null
    use_masking: true
    bce_pos_weight: 5.0
    use_guided_attn_loss: true
    guided_attn_loss_sigma: 0.4
    guided_attn_loss_lambda: 1.0
required:
- output_dir
- token_list
distributed: false
