apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-lite:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 30s