version: '3.8'

services:
  # 后端开发模式
  backend:
    environment:
      - DEBUG=true
      - RELOAD=true
    volumes:
      - ./platform/backend/app:/app/app  # 代码热重载
      - ./platform/backend/requirements.txt:/app/requirements.txt  # 依赖文件
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app/app"] 