version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.correct
    container_name: ai-sound-backend
    environment:
      - DATABASE_URL=postgresql://ai_sound_user:ai_sound_password@database:5432/ai_sound
      - MEGATTS3_URL=http://host.docker.internal:9000
      - AUDIO_DIR=/app/data/audio
      - UPLOADS_DIR=/app/data/uploads
      - VOICE_PROFILES_DIR=/app/data/voice_profiles
      - DEBUG=false
    volumes:
      - ./data:/app/data
    depends_on:
      - database
      - redis
    networks:
      - ai-sound-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 数据库服务
  database:
    image: postgres:15-alpine
    container_name: ai-sound-db
    environment:
      - POSTGRES_DB=ai_sound
      - POSTGRES_USER=ai_sound_user
      - POSTGRES_PASSWORD=ai_sound_password
    volumes:
      - ./data/database:/var/lib/postgresql/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ai-sound-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_sound_user -d ai_sound"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: ai-sound-redis
    command: redis-server --appendonly yes
    volumes:
      - ./data/cache:/data
    networks:
      - ai-sound-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx网关
  nginx:
    image: nginx:alpine
    container_name: ai-sound-nginx
    ports:
      - "3001:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx-dist:/usr/share/nginx/html:ro
      - ./data/audio:/usr/share/nginx/audio:ro
      - ./data/voice_profiles:/usr/share/nginx/voice_profiles:ro
      - ./data/logs/nginx:/var/log/nginx
    depends_on:
      - backend
    networks:
      - ai-sound-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ai-sound-network:
    driver: bridge
    name: ai-sound-network

volumes:
  postgres_data:
  redis_data: