version: '3.8'

services:
  megatts3-api:
    image: megatts3:latest
    container_name: megatts3-api
    command: ["/bin/bash", "-c", "cd /app/src/api && python server.py"]
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/app:/app/MegaTTS3
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8001
    volumes:
      - ./src:/app/src
      - ../../../MegaTTS/MegaTTS3:/app/MegaTTS3:ro
      - ./models:/app/models:ro
      - ./storage:/app/storage
      - ./logs:/app/logs
      - ./config:/app/config:ro
    ports:
      - "8001:8001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - ai-sound-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  megatts3-webui:
    image: megatts3:latest
    container_name: megatts3-webui
    command: ["/bin/bash", "-c", "cd /app/src/webui && python gradio_app.py"]
    environment:
      - PYTHONPATH=/app
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=8002
      - MEGATTS3_API_URL=http://megatts3-api:8001
    volumes:
      - ./src:/app/src
      - ./config:/app/config:ro
    ports:
      - "8002:8002"
    depends_on:
      - megatts3-api
    restart: unless-stopped
    networks:
      - ai-sound-network

networks:
  ai-sound-network:
    driver: bridge
    name: ai-sound-microservices
    external: true

volumes:
  megatts3-models:
    driver: local
  megatts3-storage:
    driver: local
  megatts3-logs:
    driver: local 