version: '3.8'

services:
  nginx-gateway:
    image: nginx:alpine
    container_name: ai-sound-gateway
    ports:
      - "7929:7929"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - ai-sound-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7929/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ai-sound-network:
    driver: bridge
    name: ai-sound-microservices 