version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    container_name: ai-sound-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ai-sound-network
    restart: unless-stopped

  # 后端服务
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    container_name: ai-sound-backend
    ports:
      - "8000:8000"
    volumes:
      - ../storage:/app/storage
    environment:
      - DATABASE_PATH=/app/storage/database/ai_sound.db
      - MEGATTS3_URL=http://megatts3:9000
      - AUDIO_DIR=/app/storage/audio
      - UPLOADS_DIR=/app/storage/uploads
      - VOICE_PROFILES_DIR=/app/storage/voice_profiles
    depends_on:
      - database
      - redis
    networks:
      - ai-sound-network
    restart: unless-stopped

  # 数据库服务
  database:
    image: postgres:15-alpine
    container_name: ai-sound-database
    environment:
      - POSTGRES_DB=ai_sound
      - POSTGRES_USER=ai_sound_user
      - POSTGRES_PASSWORD=ai_sound_password
    volumes:
      - ../storage/database:/var/lib/postgresql/data
      - ../docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ai-sound-network
    restart: unless-stopped

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: ai-sound-redis
    command: redis-server --appendonly yes
    volumes:
      - ../storage/redis:/data
    networks:
      - ai-sound-network
    restart: unless-stopped

  # Nginx网关
  nginx:
    image: nginx:alpine
    container_name: ai-sound-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../docker/nginx/ssl:/etc/nginx/ssl:ro
      - ../storage/audio:/usr/share/nginx/audio:ro
    depends_on:
      - frontend
      - backend
    networks:
      - ai-sound-network
    restart: unless-stopped

  # MegaTTS3引擎
  megatts3:
    extends:
      file: ../docker/megatts3/docker-compose.yml
      service: megatts3
    networks:
      - ai-sound-network

networks:
  ai-sound-network:
    driver: bridge
    name: ai-sound-network

volumes:
  postgres_data:
  redis_data: 