services:
  # 后端API服务
  api:
    build:
      context: ..
      dockerfile: ./services/api/Dockerfile
    image: ai-sound-api:latest
    command: ["python3", "src/main.py", "--host", "0.0.0.0", "--port", "9930"]
    ports:
      - "9930:9930"
    volumes:
      - ../data/output:/app/output
      - ../data/temp:/app/data
      - ../MegaTTS/MegaTTS3:/app/MegaTTS3
    environment:
      - OUTPUT_DIR=/app/output
      - API_HOST=0.0.0.0
      - API_PORT=9930
      - PYTHONPATH=/app:/app/MegaTTS3
      # 引擎服务URL配置（指向外部服务）
      - MEGATTS3_URL=http://host.docker.internal:7929
      - ESPNET_URL=http://host.docker.internal:9001
      - BERTVITS2_URL=http://host.docker.internal:9932
      # MongoDB配置 - 连接到独立的基础设施服务
      - DB_HOST=ai-sound-mongodb
      - DB_PORT=27017
      - DB_DATABASE=ai_sound
      - DB_USERNAME=ai_sound_user
      - DB_PASSWORD=ai_sound_pass_2024
    networks:
      - ai-sound-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9930/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  # Web前端管理界面
  web-admin:
    build: ./web-admin
    image: ai-sound-web-admin:latest
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:9930
    depends_on:
      - api
    networks:
      - ai-sound-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

# 网络配置 - 连接到基础设施网络
networks:
  ai-sound-network:
    name: ai-sound-network
    external: true 