version: '3.8'

services:
  songgeneration:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    container_name: songgeneration-service
    ports:
      - "7862:7862"
    volumes:
      - ./output:/app/output
      - ./temp:/app/temp
      - ./ckpt:/app/ckpt:ro  # 只读挂载模型文件
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7862
    restart: unless-stopped
    # GPU支持已启用
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 