service:
  name: megatts3
  version: "1.0.0"
  type: tts
  description: "MegaTTS3 Text-to-Speech Service"

api:
  host: "0.0.0.0"
  port: 8001
  version: "v1"
  cors: true

webui:
  host: "0.0.0.0"
  port: 8002
  title: "MegaTTS3 WebUI"

models:
  base_path: "/app/models"
  cache_dir: "/app/storage/cache"
  default_model: "megatts3_dit"

gpu:
  enabled: true
  device_id: 0
  memory_limit: "4GB"

logging:
  level: "INFO"
  file: "/app/logs/megatts3.log"
  max_size: "100MB"
  backup_count: 5 