espnet: 0.10.3a2
files:
  model_file: exp/tts_train_vits_raw_phn_pypinyin_g2p_phone/train.total_count.ave_10best.pth
python: "3.7.3 (default, Mar 27 2019, 22:11:17) \n[GCC 7.3.0]"
timestamp: 1631247396.642391
torch: 1.7.1
yaml_files:
  train_config: exp/tts_train_vits_raw_phn_pypinyin_g2p_phone/config.yaml
