FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY espnet_mock.py .

# 创建临时目录
RUN mkdir -p /app/temp

# 暴露端口
EXPOSE 9932

# 启动服务
CMD ["python", "espnet_mock.py"]